image:
   name: hashicorp/terraform:light
   entrypoint:
     - '/usr/bin/env'
     - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
      - validate
      - plan
      - apply
      - dbt_test
      - dbt_run
      - destory

validate:
  stage: validate
  before_script:
      -  rm -rf .terraform
      -  terraform --version
      -  mkdir -p ./creds
      -  echo $SERVICEACCOUNT | base64 -d > ./creds/serviceaccount.json
      -  terraform -chdir=terraform init
  script:
     - terraform -chdir=terraform validate

plan:
  stage: plan
  before_script:
      -  rm -rf .terraform
      -  terraform --version
      -  mkdir -p ./creds
      -  echo $SERVICEACCOUNT | base64 -d > ./creds/serviceaccount.json
      -  terraform -chdir=terraform init  
  script:
  - export TF_VAR_branch=dev
  - export TF_VAR_suffix=wayne   
  - terraform -chdir=terraform plan -out planfile
  dependencies:
    - validate
  artifacts:
    paths:
      - ./terraform/planfile

apply:
  stage: apply
  before_script:
      -  rm -rf .terraform
      -  terraform --version
      -  mkdir -p ./creds
      -  echo $SERVICEACCOUNT | base64 -d > ./creds/serviceaccount.json
      -  terraform -chdir=terraform init
  script:
    - export TF_VAR_branch=dev
    - export TF_VAR_suffix=wayne
    - terraform -chdir=terraform apply -input=false planfile
  dependencies:
    - plan

destory:
  stage: destory
  before_script:
      -  rm -rf .terraform
      -  terraform --version
      -  mkdir -p ./creds
      -  echo $SERVICEACCOUNT | base64 -d > ./creds/serviceaccount.json
      -  terraform -chdir=terraform init
  script:
    - terraform -chdir=terraform destroy -auto-approve
  dependencies:
    - apply
    - plan
  when: manual

run_sample_big_query:
  image: python:3.10-slim-buster
  stage: dbt_run
  before_script:
      -  mkdir -p ./creds
      -  echo $SERVICEACCOUNT | base64 -d > ./creds/serviceaccount.json
  script:
    - export DBT_PROFILES_DIR="./dbt_profiles"
    - export DBT_ENVIRONMENT=dev
    - cd dbt
    - pip install -r requirements.txt
    - cd dbt_sample_bigquery
    - dbt run