dbt_sample_bigquery:
  outputs:
    dev:
      dataset: stock_us
      job_execution_timeout_seconds: 3600
      job_retries: 1
      keyfile: ../../creds/serviceaccount.json
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      threads: 1
      type: bigquery
  target: dev
