name: Run TF and DBT scripts

on: [push]  # This triggers the workflow on every push to the repository

jobs:
  tf_validate:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:light
      options: --entrypoint '/usr/bin/env'
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE
    - name: prepare tf
      run: |
        rm -rf .terraform
        terraform --version
        mkdir -p ./creds
        echo ${{ secrets.SERVICE_ACCOUNT }} | base64 -d > ./creds/serviceaccount.json
    - name: validate
      run: |
        terraform -chdir=terraform init

  tf_plan:
    needs: tf_validate
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:light
      options: --entrypoint '/usr/bin/env'
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE
    - name: prepare tf
      run: |
        rm -rf .terraform
        terraform --version
        mkdir -p ./creds
        echo ${{ secrets.SERVICE_ACCOUNT }} | base64 -d > ./creds/serviceaccount.json
    - name: plan
      run: |
        export TF_VAR_branch=dev
        export TF_VAR_suffix=wayne   
        terraform -chdir=terraform init
        terraform -chdir=terraform plan -out planfile
    - name: Save Terraform Plan File as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: terraform-planfile
        path: ./terraform/planfile

  tf_apply:
    needs: tf_plan
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform:light
      options: --entrypoint '/usr/bin/env'
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE
    - name: prepare tf
      run: |
        rm -rf .terraform
        terraform --version
        mkdir -p ./creds
        echo ${{ secrets.SERVICE_ACCOUNT }} | base64 -d > ./creds/serviceaccount.json
    - name: Download Terraform Plan
      uses: actions/download-artifact@v2
      with:
        name: terraform-planfile
        path: ./terraform      
    - name: apply
      run: |
        export TF_VAR_branch=dev
        export TF_VAR_suffix=wayne   
        terraform -chdir=terraform init
        terraform -chdir=terraform apply -input=false planfile

  run_sample_big_query:
    needs: tf_apply
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim-buster  # Specifies the runner environment

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE

    - name: authenticate to gcp
      run: |
        mkdir -p ./creds
        echo ${{ secrets.SERVICE_ACCOUNT }} | base64 -d > ./creds/serviceaccount.json
        echo "---"
        echo ${{ vars.GCP_PROJECT_ID }}
        echo "---"
    - name: run dbt
      run: |
        export DBT_PROFILES_DIR="./dbt_profiles"
        export DBT_ENVIRONMENT=dev
        export GCP_PROJECT_ID=${{ vars.GCP_PROJECT_ID }}
        cd dbt
        pip install -r requirements.txt
        cd dbt_sample_bigquery
        dbt run
